/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'title' : string,
  'chapterNumber' : number,
  'createdAt' : bigint,
  'comicId' : bigint,
  'mangadexChapterId' : [] | [string],
}
export interface Comic {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'coverBlobId' : [] | [string],
  'sourceType' : string,
  'updatedAt' : bigint,
  'synopsis' : string,
  'viewCount' : bigint,
  'genres' : Array<string>,
  'isExplicit' : boolean,
}
export interface Comment {
  'id' : bigint,
  'username' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'comicId' : bigint,
}
export interface Page {
  'id' : bigint,
  'pageNumber' : bigint,
  'chapterId' : bigint,
  'blobId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], undefined>,
  'addPage' : ActorMethod<[bigint, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChapter' : ActorMethod<[bigint, number, string], bigint>,
  'createComic' : ActorMethod<
    [string, [] | [string], Array<string>, string, string, string, boolean],
    bigint
  >,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteComic' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'fetchMangaDexChapterPages' : ActorMethod<[bigint], undefined>,
  'fetchMangaDexChapters' : ActorMethod<[string, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComic' : ActorMethod<[bigint], Comic>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grabChapterPages' : ActorMethod<
    [bigint, bigint, string, bigint, bigint],
    undefined
  >,
  'importFromMangaDex' : ActorMethod<[string], bigint>,
  'incrementViewCount' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllGenres' : ActorMethod<[], Array<string>>,
  'listChaptersByComic' : ActorMethod<[bigint], Array<Chapter>>,
  'listComics' : ActorMethod<[bigint, bigint, string], Array<Comic>>,
  'listCommentsByComic' : ActorMethod<[bigint], Array<Comment>>,
  'listPagesByChapter' : ActorMethod<[bigint], Array<Page>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchComics' : ActorMethod<
    [string, [] | [string], [] | [string]],
    Array<Comic>
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateComic' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      Array<string>,
      string,
      string,
      string,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];