/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comic = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'coverBlobId' : IDL.Opt(IDL.Text),
  'sourceType' : IDL.Text,
  'updatedAt' : IDL.Int,
  'synopsis' : IDL.Text,
  'viewCount' : IDL.Nat,
  'genres' : IDL.Vec(IDL.Text),
  'isExplicit' : IDL.Bool,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'chapterNumber' : IDL.Float64,
  'createdAt' : IDL.Int,
  'comicId' : IDL.Nat,
  'mangadexChapterId' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'comicId' : IDL.Nat,
});
export const Page = IDL.Record({
  'id' : IDL.Nat,
  'pageNumber' : IDL.Nat,
  'chapterId' : IDL.Nat,
  'blobId' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addPage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChapter' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text], [IDL.Nat], []),
  'createComic' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteComic' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'fetchMangaDexChapterPages' : IDL.Func([IDL.Nat], [], []),
  'fetchMangaDexChapters' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComic' : IDL.Func([IDL.Nat], [Comic], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grabChapterPages' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'importFromMangaDex' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listChaptersByComic' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
  'listComics' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Vec(Comic)],
      ['query'],
    ),
  'listCommentsByComic' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'listPagesByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Page)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchComics' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Comic)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateComic' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comic = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'coverBlobId' : IDL.Opt(IDL.Text),
    'sourceType' : IDL.Text,
    'updatedAt' : IDL.Int,
    'synopsis' : IDL.Text,
    'viewCount' : IDL.Nat,
    'genres' : IDL.Vec(IDL.Text),
    'isExplicit' : IDL.Bool,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'chapterNumber' : IDL.Float64,
    'createdAt' : IDL.Int,
    'comicId' : IDL.Nat,
    'mangadexChapterId' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'comicId' : IDL.Nat,
  });
  const Page = IDL.Record({
    'id' : IDL.Nat,
    'pageNumber' : IDL.Nat,
    'chapterId' : IDL.Nat,
    'blobId' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addPage' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChapter' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text], [IDL.Nat], []),
    'createComic' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteComic' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'fetchMangaDexChapterPages' : IDL.Func([IDL.Nat], [], []),
    'fetchMangaDexChapters' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComic' : IDL.Func([IDL.Nat], [Comic], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grabChapterPages' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'importFromMangaDex' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllGenres' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listChaptersByComic' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
    'listComics' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Vec(Comic)],
        ['query'],
      ),
    'listCommentsByComic' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'listPagesByChapter' : IDL.Func([IDL.Nat], [IDL.Vec(Page)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchComics' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Comic)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateComic' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };